export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const STASH_SEEN_MESSAGES = 'STASH_SEEN_MESSAGES';
export const CLEAR_STASH = 'CLEAR_STASH';
